---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Install in your local dev environment
# > pip install --upgrade --user pre-commit
# Enable the hooks for this repo
# > pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files  # Check for large files
      - id: check-merge-conflict     # Check for merge conflict strings
      - id: fix-byte-order-marker    # Forbid utf-8 byte order marker
      - id: end-of-file-fixer        # Files end w/ newline
      - id: trailing-whitespace      # Trims trailing whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.32.0"
    hooks:
      - id: yamllint
        args: ["--strict"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.37.0"
    hooks:
      - id: markdownlint
